export default {
    qiyeData: [{
        cityName: "昆明市",
        cityCode: "530100",
    }, {
        cityName: "曲靖市",
        cityCode: "530300",
    }, {
        cityName: "玉溪市",
        cityCode: "530400",
    }, {
        cityName: "保山市",
        cityCode: "530500",
    }, {
        cityName: "昭通市",
        cityCode: "530600",
    }, {
        cityName: "丽江市",
        cityCode: "530700",
    }, {
        cityName: "普洱市",
        cityCode: "530800",
    }, {
        cityName: "临沧市",
        cityCode: "530900",
    }, {
        cityName: "楚雄彝族自治州",
        cityCode: "532300",
    }, {
        cityName: "红河哈尼族彝族自治州",
        cityCode: "532500",
    }, {
        cityName: "文山壮族苗族自治州",
        cityCode: "532600",
    }, {
        cityName: "西双版纳傣族自治州",
        cityCode: "532800",
    }, {
        cityName: "大理白族自治州",
        cityCode: "532900",
    }, {
        cityName: "德宏傣族景颇族自治州",
        cityCode: "533100",
    }, {
        cityName: "怒江傈僳族自治州",
        cityCode: "533300",
    }, {
        cityName: "迪庆藏族自治州",
        cityCode: "533400",
    }]
};